### ISSUE TITLE
最后面算px和dp转换的dp2px方法里面返回有个0.5f什么意思。。

### ISSUE THREAD

**Issue by 516457377** [JeasonWong/SlackLoadingView#3]
private int dp2px(Context context, float dp) {
        final float scale = context.getResources().getDisplayMetrics().density;
        return (int) (dp \* scale + 0.5f);
    }
感觉没多大用啊

**Comment by 516457377** [comment]
感谢作者，我用了两天，，终于学会了自定义动画效果了

**Comment by SheepYang1993** [comment]
@516457377 四舍五入保证精度

**Comment by 516457377** [comment]
@SheepYang1993 没太懂。。0.5个像素。。怎么个保精度。。

**Comment by JeasonWong** [comment]
@516457377 

http://developer.android.com/guide/practices/screens_support.html

> Then add 0.5f to round the figure up to the nearest whole number, when converting to an integer.
